import { boolean, index, int, json, mysqlTable, text, timestamp, tinyint, varchar } from 'drizzle-orm/mysql-core'
import { createInsertSchema, createSelectSchema } from 'drizzle-typebox'
import { t } from 'elysia'

export const projects = mysqlTable('projects', {
  id: int('id').primaryKey().autoincrement(),
  userId: varchar('user_id', { length: 255 }).notNull(),
  status: tinyint('status').notNull().default(0),
  likeCount: int('like_count').notNull().default(0),
  name: varchar('name', { length: 255 }).notNull(),
  tagline: varchar('tagline', { length: 255 }),
  description: text('description'),
  coverUrl: varchar('cover_url', { length: 255 }),
  demoImages: json('demo_images').$type<string[]>(),
  demoVideoUrl: varchar('demo_video_url', { length: 255 }),
  demoLink: varchar('demo_link', { length: 255 }),
  stage: tinyint('stage'),
  categories: json('categories').$type<string[]>(),
  targetUsers: text('target_users'),
  userProblem: text('user_problem'),
  progress: text('progress'),
  nextSteps: text('next_steps'),
  messageToUsers: text('message_to_users'),
  isOpenForBeta: boolean('is_open_for_beta'),
  betaDescription: text('beta_description'),
  contactName: varchar('contact_name', { length: 255 }),
  contactPhone: varchar('contact_phone', { length: 255 }),
  contactEmail: varchar('contact_email', { length: 255 }),
  contactWechat: varchar('contact_wechat', { length: 255 }),
  teamName: varchar('team_name', { length: 255 }),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow().onUpdateNow(),
}, (table) => [
  index('idx_projects_user_id').on(table.userId),
  index('idx_projects_status').on(table.status),
  index('idx_projects_stage').on(table.stage),
])

export const InsertProject = createInsertSchema(projects, {
  id: undefined,
  createdAt: undefined,
  updatedAt: undefined,
  name: (schema) => t.String({ ...schema, minLength: 1, description: 'Project name' }),
  tagline: (s) => { s.description = 'One-line project tagline'; return s },
  description: (s) => { s.description = 'Detailed project description'; return s },
  coverUrl: (s) => { s.description = 'Cover image URL'; return s },
  demoImages: t.Optional(t.Union([t.Array(t.String()), t.Null()], { description: 'Demo screenshot URLs' })),
  demoVideoUrl: (s) => { s.description = 'Demo video URL'; return s },
  demoLink: (s) => { s.description = 'Live demo or product link'; return s },
  stage: (s) => { s.description = 'Product stage: 0 = MVP, 1 = Growth'; return s },
  categories: t.Optional(t.Union([t.Array(t.String()), t.Null()], { description: 'Product categories' })),
  targetUsers: (s) => { s.description = 'Target user description'; return s },
  userProblem: (s) => { s.description = 'Problem being solved for users'; return s },
  progress: (s) => { s.description = 'Current development progress'; return s },
  nextSteps: (s) => { s.description = 'Planned next steps'; return s },
  messageToUsers: (s) => { s.description = 'Message to potential users'; return s },
  isOpenForBeta: (s) => { s.description = 'Whether beta testing is open'; return s },
  betaDescription: (s) => { s.description = 'Beta program description (required when isOpenForBeta is true)'; return s },
  contactName: (s) => { s.description = 'Contact person name'; return s },
  contactPhone: (s) => { s.description = 'Contact phone number'; return s },
  contactEmail: (s) => { s.description = 'Contact email address'; return s },
  contactWechat: (s) => { s.description = 'Contact WeChat ID'; return s },
  teamName: (s) => { s.description = 'Team or company name'; return s },
})
export type InsertProject = typeof InsertProject.static

export const SelectProject = createSelectSchema(projects, {
  id: (s) => { s.description = 'Unique project identifier'; return s },
  userId: (s) => { s.description = 'Owner user ID (from external auth)'; return s },
  status: (s) => { s.description = 'Lifecycle status: 0=Draft, 1=PendingReview, 2=RevisionRequired, 3=Live, 4=Delisted, 5=Rejected'; return s },
  likeCount: (s) => { s.description = 'Number of users who like this project'; return s },
  name: (s) => { s.description = 'Project name'; return s },
  tagline: (s) => { s.description = 'One-line project tagline'; return s },
  description: (s) => { s.description = 'Detailed project description'; return s },
  coverUrl: (s) => { s.description = 'Cover image URL'; return s },
  demoImages: (s) => { s.description = 'Demo screenshot URLs'; return s },
  demoVideoUrl: (s) => { s.description = 'Demo video URL'; return s },
  demoLink: (s) => { s.description = 'Live demo or product link'; return s },
  stage: (s) => { s.description = 'Product stage: 0=MVP, 1=Growth'; return s },
  categories: (s) => { s.description = 'Product categories'; return s },
  targetUsers: (s) => { s.description = 'Target user description'; return s },
  userProblem: (s) => { s.description = 'Problem being solved for users'; return s },
  progress: (s) => { s.description = 'Current development progress'; return s },
  nextSteps: (s) => { s.description = 'Planned next steps'; return s },
  messageToUsers: (s) => { s.description = 'Message to potential users'; return s },
  isOpenForBeta: (s) => { s.description = 'Whether beta testing is open'; return s },
  betaDescription: (s) => { s.description = 'Beta program description'; return s },
  contactName: (s) => { s.description = 'Contact person name'; return s },
  contactPhone: (s) => { s.description = 'Contact phone number'; return s },
  contactEmail: (s) => { s.description = 'Contact email address'; return s },
  contactWechat: (s) => { s.description = 'Contact WeChat ID'; return s },
  teamName: (s) => { s.description = 'Team or company name'; return s },
  createdAt: (s) => { s.description = 'Creation timestamp'; return s },
  updatedAt: (s) => { s.description = 'Last update timestamp'; return s },
})
export type SelectProject = typeof SelectProject.static
